// Generated by gencpp from file myPKG/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MYPKG_MESSAGE_ADDTWOINTS_H
#define MYPKG_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <myPKG/AddTwoIntsRequest.h>
#include <myPKG/AddTwoIntsResponse.h>


namespace myPKG
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace myPKG


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myPKG::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::myPKG::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::myPKG::AddTwoInts > {
  static const char* value()
  {
    return "myPKG/AddTwoInts";
  }

  static const char* value(const ::myPKG::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::myPKG::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::myPKG::AddTwoInts > 
template<>
struct MD5Sum< ::myPKG::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myPKG::AddTwoInts >::value();
  }
  static const char* value(const ::myPKG::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPKG::AddTwoIntsRequest> should match 
// service_traits::DataType< ::myPKG::AddTwoInts > 
template<>
struct DataType< ::myPKG::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::myPKG::AddTwoInts >::value();
  }
  static const char* value(const ::myPKG::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myPKG::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::myPKG::AddTwoInts > 
template<>
struct MD5Sum< ::myPKG::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myPKG::AddTwoInts >::value();
  }
  static const char* value(const ::myPKG::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myPKG::AddTwoIntsResponse> should match 
// service_traits::DataType< ::myPKG::AddTwoInts > 
template<>
struct DataType< ::myPKG::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::myPKG::AddTwoInts >::value();
  }
  static const char* value(const ::myPKG::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYPKG_MESSAGE_ADDTWOINTS_H
