// Generated by gencpp from file level_three/cmd_msg.msg
// DO NOT EDIT!


#ifndef LEVEL_THREE_MESSAGE_CMD_MSG_H
#define LEVEL_THREE_MESSAGE_CMD_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace level_three
{
template <class ContainerAllocator>
struct cmd_msg_
{
  typedef cmd_msg_<ContainerAllocator> Type;

  cmd_msg_()
    : cmd_msg()  {
    }
  cmd_msg_(const ContainerAllocator& _alloc)
    : cmd_msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _cmd_msg_type;
  _cmd_msg_type cmd_msg;




  typedef boost::shared_ptr< ::level_three::cmd_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::level_three::cmd_msg_<ContainerAllocator> const> ConstPtr;

}; // struct cmd_msg_

typedef ::level_three::cmd_msg_<std::allocator<void> > cmd_msg;

typedef boost::shared_ptr< ::level_three::cmd_msg > cmd_msgPtr;
typedef boost::shared_ptr< ::level_three::cmd_msg const> cmd_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::level_three::cmd_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::level_three::cmd_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace level_three

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'level_three': ['/home/ros/catkin_ws/src/level_three/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::level_three::cmd_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::level_three::cmd_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::level_three::cmd_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::level_three::cmd_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::level_three::cmd_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::level_three::cmd_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::level_three::cmd_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71f25e80beb7e45806f82da575102343";
  }

  static const char* value(const ::level_three::cmd_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71f25e80beb7e458ULL;
  static const uint64_t static_value2 = 0x06f82da575102343ULL;
};

template<class ContainerAllocator>
struct DataType< ::level_three::cmd_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "level_three/cmd_msg";
  }

  static const char* value(const ::level_three::cmd_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::level_three::cmd_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist cmd_msg\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::level_three::cmd_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::level_three::cmd_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cmd_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::level_three::cmd_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::level_three::cmd_msg_<ContainerAllocator>& v)
  {
    s << indent << "cmd_msg: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEVEL_THREE_MESSAGE_CMD_MSG_H
