// Generated by gencpp from file exp6_524/DoSquare.msg
// DO NOT EDIT!


#ifndef EXP6_524_MESSAGE_DOSQUARE_H
#define EXP6_524_MESSAGE_DOSQUARE_H

#include <ros/service_traits.h>


#include <exp6_524/DoSquareRequest.h>
#include <exp6_524/DoSquareResponse.h>


namespace exp6_524
{

struct DoSquare
{

typedef DoSquareRequest Request;
typedef DoSquareResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DoSquare
} // namespace exp6_524


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exp6_524::DoSquare > {
  static const char* value()
  {
    return "397e5d9373b2d6be3b1e90928218304b";
  }

  static const char* value(const ::exp6_524::DoSquare&) { return value(); }
};

template<>
struct DataType< ::exp6_524::DoSquare > {
  static const char* value()
  {
    return "exp6_524/DoSquare";
  }

  static const char* value(const ::exp6_524::DoSquare&) { return value(); }
};


// service_traits::MD5Sum< ::exp6_524::DoSquareRequest> should match 
// service_traits::MD5Sum< ::exp6_524::DoSquare > 
template<>
struct MD5Sum< ::exp6_524::DoSquareRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exp6_524::DoSquare >::value();
  }
  static const char* value(const ::exp6_524::DoSquareRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exp6_524::DoSquareRequest> should match 
// service_traits::DataType< ::exp6_524::DoSquare > 
template<>
struct DataType< ::exp6_524::DoSquareRequest>
{
  static const char* value()
  {
    return DataType< ::exp6_524::DoSquare >::value();
  }
  static const char* value(const ::exp6_524::DoSquareRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exp6_524::DoSquareResponse> should match 
// service_traits::MD5Sum< ::exp6_524::DoSquare > 
template<>
struct MD5Sum< ::exp6_524::DoSquareResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exp6_524::DoSquare >::value();
  }
  static const char* value(const ::exp6_524::DoSquareResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exp6_524::DoSquareResponse> should match 
// service_traits::DataType< ::exp6_524::DoSquare > 
template<>
struct DataType< ::exp6_524::DoSquareResponse>
{
  static const char* value()
  {
    return DataType< ::exp6_524::DoSquare >::value();
  }
  static const char* value(const ::exp6_524::DoSquareResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXP6_524_MESSAGE_DOSQUARE_H
