// Generated by gencpp from file exp6_524/DoSquareResponse.msg
// DO NOT EDIT!


#ifndef EXP6_524_MESSAGE_DOSQUARERESPONSE_H
#define EXP6_524_MESSAGE_DOSQUARERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exp6_524
{
template <class ContainerAllocator>
struct DoSquareResponse_
{
  typedef DoSquareResponse_<ContainerAllocator> Type;

  DoSquareResponse_()
    : success(false)  {
    }
  DoSquareResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::exp6_524::DoSquareResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exp6_524::DoSquareResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DoSquareResponse_

typedef ::exp6_524::DoSquareResponse_<std::allocator<void> > DoSquareResponse;

typedef boost::shared_ptr< ::exp6_524::DoSquareResponse > DoSquareResponsePtr;
typedef boost::shared_ptr< ::exp6_524::DoSquareResponse const> DoSquareResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exp6_524::DoSquareResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exp6_524::DoSquareResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exp6_524

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'exp6_524': ['/home/ros/catkin_ws/src/exp6_524/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exp6_524::DoSquareResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exp6_524::DoSquareResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exp6_524::DoSquareResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::exp6_524::DoSquareResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exp6_524/DoSquareResponse";
  }

  static const char* value(const ::exp6_524::DoSquareResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const ::exp6_524::DoSquareResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoSquareResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exp6_524::DoSquareResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exp6_524::DoSquareResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXP6_524_MESSAGE_DOSQUARERESPONSE_H
