// Generated by gencpp from file pro_turtlebot_s/Location_monitor.msg
// DO NOT EDIT!


#ifndef PRO_TURTLEBOT_S_MESSAGE_LOCATION_MONITOR_H
#define PRO_TURTLEBOT_S_MESSAGE_LOCATION_MONITOR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pro_turtlebot_s
{
template <class ContainerAllocator>
struct Location_monitor_
{
  typedef Location_monitor_<ContainerAllocator> Type;

  Location_monitor_()
    : name()
    , distance(0.0)  {
    }
  Location_monitor_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> const> ConstPtr;

}; // struct Location_monitor_

typedef ::pro_turtlebot_s::Location_monitor_<std::allocator<void> > Location_monitor;

typedef boost::shared_ptr< ::pro_turtlebot_s::Location_monitor > Location_monitorPtr;
typedef boost::shared_ptr< ::pro_turtlebot_s::Location_monitor const> Location_monitorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator1> & lhs, const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator1> & lhs, const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pro_turtlebot_s

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2f8ddf8c9e39a28149179429f5ae342";
  }

  static const char* value(const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2f8ddf8c9e39a28ULL;
  static const uint64_t static_value2 = 0x149179429f5ae342ULL;
};

template<class ContainerAllocator>
struct DataType< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pro_turtlebot_s/Location_monitor";
  }

  static const char* value(const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"float64 distance\n"
;
  }

  static const char* value(const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Location_monitor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pro_turtlebot_s::Location_monitor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pro_turtlebot_s::Location_monitor_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRO_TURTLEBOT_S_MESSAGE_LOCATION_MONITOR_H
