// Generated by gencpp from file pro_turtlebot_s/turtle_control.msg
// DO NOT EDIT!


#ifndef PRO_TURTLEBOT_S_MESSAGE_TURTLE_CONTROL_H
#define PRO_TURTLEBOT_S_MESSAGE_TURTLE_CONTROL_H

#include <ros/service_traits.h>


#include <pro_turtlebot_s/turtle_controlRequest.h>
#include <pro_turtlebot_s/turtle_controlResponse.h>


namespace pro_turtlebot_s
{

struct turtle_control
{

typedef turtle_controlRequest Request;
typedef turtle_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turtle_control
} // namespace pro_turtlebot_s


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pro_turtlebot_s::turtle_control > {
  static const char* value()
  {
    return "cb5a2ff85b3ab0fa811ff6800544146e";
  }

  static const char* value(const ::pro_turtlebot_s::turtle_control&) { return value(); }
};

template<>
struct DataType< ::pro_turtlebot_s::turtle_control > {
  static const char* value()
  {
    return "pro_turtlebot_s/turtle_control";
  }

  static const char* value(const ::pro_turtlebot_s::turtle_control&) { return value(); }
};


// service_traits::MD5Sum< ::pro_turtlebot_s::turtle_controlRequest> should match
// service_traits::MD5Sum< ::pro_turtlebot_s::turtle_control >
template<>
struct MD5Sum< ::pro_turtlebot_s::turtle_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pro_turtlebot_s::turtle_control >::value();
  }
  static const char* value(const ::pro_turtlebot_s::turtle_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pro_turtlebot_s::turtle_controlRequest> should match
// service_traits::DataType< ::pro_turtlebot_s::turtle_control >
template<>
struct DataType< ::pro_turtlebot_s::turtle_controlRequest>
{
  static const char* value()
  {
    return DataType< ::pro_turtlebot_s::turtle_control >::value();
  }
  static const char* value(const ::pro_turtlebot_s::turtle_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pro_turtlebot_s::turtle_controlResponse> should match
// service_traits::MD5Sum< ::pro_turtlebot_s::turtle_control >
template<>
struct MD5Sum< ::pro_turtlebot_s::turtle_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pro_turtlebot_s::turtle_control >::value();
  }
  static const char* value(const ::pro_turtlebot_s::turtle_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pro_turtlebot_s::turtle_controlResponse> should match
// service_traits::DataType< ::pro_turtlebot_s::turtle_control >
template<>
struct DataType< ::pro_turtlebot_s::turtle_controlResponse>
{
  static const char* value()
  {
    return DataType< ::pro_turtlebot_s::turtle_control >::value();
  }
  static const char* value(const ::pro_turtlebot_s::turtle_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRO_TURTLEBOT_S_MESSAGE_TURTLE_CONTROL_H
