// Generated by gencpp from file exp7_524/AddThreeInts.msg
// DO NOT EDIT!


#ifndef EXP7_524_MESSAGE_ADDTHREEINTS_H
#define EXP7_524_MESSAGE_ADDTHREEINTS_H

#include <ros/service_traits.h>


#include <exp7_524/AddThreeIntsRequest.h>
#include <exp7_524/AddThreeIntsResponse.h>


namespace exp7_524
{

struct AddThreeInts
{

typedef AddThreeIntsRequest Request;
typedef AddThreeIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddThreeInts
} // namespace exp7_524


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exp7_524::AddThreeInts > {
  static const char* value()
  {
    return "c9caccfcada3b6a45d8528a23bccaf1a";
  }

  static const char* value(const ::exp7_524::AddThreeInts&) { return value(); }
};

template<>
struct DataType< ::exp7_524::AddThreeInts > {
  static const char* value()
  {
    return "exp7_524/AddThreeInts";
  }

  static const char* value(const ::exp7_524::AddThreeInts&) { return value(); }
};


// service_traits::MD5Sum< ::exp7_524::AddThreeIntsRequest> should match 
// service_traits::MD5Sum< ::exp7_524::AddThreeInts > 
template<>
struct MD5Sum< ::exp7_524::AddThreeIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exp7_524::AddThreeInts >::value();
  }
  static const char* value(const ::exp7_524::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exp7_524::AddThreeIntsRequest> should match 
// service_traits::DataType< ::exp7_524::AddThreeInts > 
template<>
struct DataType< ::exp7_524::AddThreeIntsRequest>
{
  static const char* value()
  {
    return DataType< ::exp7_524::AddThreeInts >::value();
  }
  static const char* value(const ::exp7_524::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exp7_524::AddThreeIntsResponse> should match 
// service_traits::MD5Sum< ::exp7_524::AddThreeInts > 
template<>
struct MD5Sum< ::exp7_524::AddThreeIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exp7_524::AddThreeInts >::value();
  }
  static const char* value(const ::exp7_524::AddThreeIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exp7_524::AddThreeIntsResponse> should match 
// service_traits::DataType< ::exp7_524::AddThreeInts > 
template<>
struct DataType< ::exp7_524::AddThreeIntsResponse>
{
  static const char* value()
  {
    return DataType< ::exp7_524::AddThreeInts >::value();
  }
  static const char* value(const ::exp7_524::AddThreeIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXP7_524_MESSAGE_ADDTHREEINTS_H
