// Generated by gencpp from file exp7/AddThreeInts.msg
// DO NOT EDIT!


#ifndef EXP7_MESSAGE_ADDTHREEINTS_H
#define EXP7_MESSAGE_ADDTHREEINTS_H

#include <ros/service_traits.h>


#include <exp7/AddThreeIntsRequest.h>
#include <exp7/AddThreeIntsResponse.h>


namespace exp7
{

struct AddThreeInts
{

typedef AddThreeIntsRequest Request;
typedef AddThreeIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddThreeInts
} // namespace exp7


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exp7::AddThreeInts > {
  static const char* value()
  {
    return "c9caccfcada3b6a45d8528a23bccaf1a";
  }

  static const char* value(const ::exp7::AddThreeInts&) { return value(); }
};

template<>
struct DataType< ::exp7::AddThreeInts > {
  static const char* value()
  {
    return "exp7/AddThreeInts";
  }

  static const char* value(const ::exp7::AddThreeInts&) { return value(); }
};


// service_traits::MD5Sum< ::exp7::AddThreeIntsRequest> should match 
// service_traits::MD5Sum< ::exp7::AddThreeInts > 
template<>
struct MD5Sum< ::exp7::AddThreeIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exp7::AddThreeInts >::value();
  }
  static const char* value(const ::exp7::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exp7::AddThreeIntsRequest> should match 
// service_traits::DataType< ::exp7::AddThreeInts > 
template<>
struct DataType< ::exp7::AddThreeIntsRequest>
{
  static const char* value()
  {
    return DataType< ::exp7::AddThreeInts >::value();
  }
  static const char* value(const ::exp7::AddThreeIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exp7::AddThreeIntsResponse> should match 
// service_traits::MD5Sum< ::exp7::AddThreeInts > 
template<>
struct MD5Sum< ::exp7::AddThreeIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exp7::AddThreeInts >::value();
  }
  static const char* value(const ::exp7::AddThreeIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exp7::AddThreeIntsResponse> should match 
// service_traits::DataType< ::exp7::AddThreeInts > 
template<>
struct DataType< ::exp7::AddThreeIntsResponse>
{
  static const char* value()
  {
    return DataType< ::exp7::AddThreeInts >::value();
  }
  static const char* value(const ::exp7::AddThreeIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXP7_MESSAGE_ADDTHREEINTS_H
